apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 6.58.8
    helm:
      values: |
        adminUser: admin
        adminPassword: admin
        persistence:
          enabled: false
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Prometheus
              type: prometheus
              url: http://prometheus-server.metrics.svc.cluster.local
              access: proxy
              isDefault: true
        dashboards:
          default:
            kubernetes-cluster:
              gnetId: 7249
              revision: 1
              datasource: Prometheus
            node-exporter:
              gnetId: 1860
              revision: 27
              datasource: Prometheus
            prometheus-stats:
              gnetId: 2
              revision: 2
              datasource: Prometheus
            app-metrics:
              gnetId: 10280
              revision: 1
              datasource: Prometheus
        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
            - name: 'default'
              orgId: 1
              folder: ''
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/default
  destination:
    server: https://kubernetes.default.svc
    namespace: metrics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true